//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by sftpplug.rc
//
#define IDD_CONNECTION                      101
#define IDI_ICON0                       102
#define IDI_ICON1                       103
#define IDD_PROPERTIES                  104
#define IDI_ICON2                       104
#define IDI_ICON1SMALL                  105
#define IDI_ICON2SMALL                  106
#define IDD_PROXY                       110
#define IDS_F7NEW                       130
#define IDS_HELPTEXT                    131
#define IDS_QUICKCONNECT                132
#define IDS_HELP_CAPTION                144
#define IDS_HELP_UTF8                   146
#define IDS_HELP_PROXY                  148
#define IDS_HELP_CERT                   149
#define IDS_CONNECT_TO                  150
#define IDS_VIA_PROXY                   151
#define IDS_ERR_PROXYCONNECT            152
#define IDS_ERR_SERVERCONNECT           153
#define IDS_VIA_PROXY_CONNECT           154
#define IDS_ERR_INIT_SSH2               155
#define IDS_ERR_SSH_SESSION             156
#define IDS_ERR_AUTH_PUBKEY             157
#define IDS_ERR_AUTH_PASSWORD           158
#define IDS_ERR_AUTH_KEYBDINT           159
#define IDS_ERR_INIT_SFTP               160
#define IDS_PROXY_PASSWORD_FOR          161
#define IDS_PROXY_PASSWORD              162
#define IDS_USERNAME_FOR                163
#define IDS_INITSSH2                    164
#define IDS_SET_COMPRESSION             165
#define IDS_SESSION_STARTUP             166
#define IDS_SSH_LOGIN                   167
#define IDS_SERVER_FINGERPRINT          168
#define IDS_CONNECTION_FIRSTTIME        169
#define IDS_FINGERPRINT_CHANGED         170
#define IDS_FINGERPRINT                 171
#define IDS_CONNECTING                  172
#define IDS_USER_AUTH_LIST              173
#define IDS_SUPPORTED_AUTH_METHODS      174
#define IDS_ERR_LOAD_PUBKEY             175
#define IDS_ERR_LOAD_PRIVKEY            176
#define IDS_ERR_PUBKEY_WRONG_FORMAT     177
#define IDS_PASSPHRASE                  178
#define IDS_KEYPASSPHRASE               179
#define IDS_AUTH_PUBKEY_FOR             180
#define IDS_AUTH_PUBKEY                 181
#define IDS_AUTH_PASSWORD_FOR           182
#define IDS_AUTH_PASSWORD               183
#define IDS_AUTH_KEYBDINT_FOR           184
#define IDS_AUTH_KEYBDINT               185
#define IDS_FTP_INIT                    186
#define IDS_DISCONNECTING               187
#define IDS_GET_DIRECTORY               188
#define IDS_PROXY_CONNECT               189
#define IDS_ERR_GETADDRINFO             190
#define IDS_GET_DIR                     191
#define IDS_ERR_GET_DIR                 192
#define IDS_MK_DIR                      193
#define IDS_ERR_MK_DIR                  194
#define IDS_RENFR                       195
#define IDS_RENTO                       196
#define IDS_ERR_RENAME                  197
#define IDS_DOWNLOAD                    198
#define IDS_UPLOAD                      199
#define IDS_DELETE                      200
#define IDS_ERR_DELETE                  201
#define IDS_AUTO                        202
#define IDS_YES                         203
#define IDS_NO                          204
#define IDS_OUTOFREACH                  205
#define IDS_FOLLOWLINKROOT              206
#define IDS_SOCKS5PROXYERR              207
#define IDS_GENERALSOCKSFAILURE         208
#define IDS_CONNNOTALLOWED              209
#define IDS_NETUNREACHABLE              210
#define IDS_HOSTUNREACHABLE             211
#define IDS_CONNREFUSED                 212
#define IDS_TTLEXPIRED                  213
#define IDS_CMDNOTSUPPORTED             214
#define IDS_ADDRTYPENOTSUPPORTED        215
#define IDS_UNKNOWNSOCKERR              216
#define IDS_DUMMY                       217
#define IDS_DUMMY2                      218
#define IDS_DUMMY3                      219
#define IDS_UTF8                        220
#define IDS_ANSI                        221
#define IDS_ASCII                       222
#define IDS_MACOS                       223
#define IDS_1250                        224
#define IDS_1251                        225
#define IDS_1252                        226
#define IDS_1253                        227
#define IDS_1254                        228
#define IDS_1255                        229
#define IDS_1256                        230
#define IDS_1257                        231
#define IDS_1258                        232
#define IDS_936                         233
#define IDS_950                         234
#define IDS_932                         235
#define IDS_949                         236
#define IDS_874                         237
#define IDS_437                         238
#define IDS_850                         239
#define IDS_20866                       240
#define IDS_OTHER                       241
#define IDS_SSH2_TOO_OLD                242
#define IDS_AGENT_CONNECTERROR          243
#define IDS_AGENT_REQUESTIDENTITIES     244
#define IDS_AGENT_AUTHFAILED            245
#define IDS_AGENT_AUTHSUCCEEDED         246
#define IDS_AGENT_NOIDENTITY            247
#define IDS_AGENT_TRYING1               248
#define IDS_AGENT_TRYING2               249
#define IDS_AGENT_TRYING3               250
#define IDS_NO_PROXY                    251
#define IDS_HTTP_PROXY                  252
#define IDS_ADD_PROXY                   253
#define IDS_ERROR_INUSE                 254
#define IDS_PROXY_PASS_TITLE            255
#define IDS_PASS_TITLE                  256
#define IDS_PASS_CHANGE_REQUEST         257
#define IDS_DLL_VERSION                 258
#define IDS_STRING258                   258
#define IDS_NO_2GB_SUPPORT              259
#define IDS_HELP_PASSWORD               260
#define IDS_TRANSFERMODE_LANPAIR        261
#define IDS_LAN_ROLE_LABEL              262
#define IDS_LAN_PEER_LABEL              263
#define IDS_LAN_ROLE_AUTO               264
#define IDS_LAN_ROLE_RECEIVER           265
#define IDS_LAN_ROLE_DONOR              266
#define IDS_LAN_PEER_AUTODISC           267
#define IDS_BUTTON_PAIR                 268
#define IDS_BUTTON_SHELL                269
#define IDS_LAN_TITLE                   270
#define IDS_LAN_ERR_PASSWORD            271
#define IDS_LAN_MSG_RECEIVER_STOPPED    272
#define IDS_LAN_ERR_RECEIVER_START      273
#define IDS_LAN_MSG_RECEIVER_STARTED    274
#define IDS_LAN_ERR_SELECT_PEER         275
#define IDS_LAN_ERR_PEER_UNAVAILABLE    276
#define IDS_LAN_ERR_PAIR_FAILED         277
#define IDS_LAN_MSG_PAIR_OK             278
#define IDC_CONNECTTO                   1000
#define IDC_USERNAME                    1001
#define IDC_PASSWORD                    1002
#define IDC_SECURE_SSL                  1003
#define IDC_PRIVKEY                     1003
#define IDC_UTF8_DIRS                   1004
#define IDC_PUBKEY                      1004
#define IDC_3STEP_UPLOAD                1005
#define IDC_3STEPHELP                   1006
#define IDC_DETAILED_LOG                1007
#define IDC_COMPRESS                    1008
#define IDC_DELETE_BEFORE_UPLOAD        1009
#define IDC_UTF8                        1009
#define IDC_DELUPLHELP                  1010
#define IDC_CRYPTPASS                   1010
#define IDC_DEFAULTCOMBO                1011
#define IDC_SCP_DATA                    1011
#define IDC_PROXYUSERNAME               1012
#define IDC_SCP_ALL                     1012
#define IDC_PROXYPASSWORD               1013
#define IDC_PROXYHELP                   1014
#define IDC_PROXYHELP2                  1015
#define IDC_PROXYSERVER                 1018
#define IDC_MULTISTEP                   1019
#define IDC_LOADPUBKEY                  1019
#define IDC_MULTISTEPHELP               1020
#define IDC_LOADPRIVKEY                 1020
#define IDC_APACHE_DIR_WITH_SLASH       1021
#define IDC_DEFAULTCOMBO2               1022
#define IDC_CBO_CC                      1022
#define IDC_LBL_CC                      1023
#define IDC_CERTHELP                    1024
#define IDC_FILEMOD                     1025
#define IDC_DIRMOD                      1026
#define IDC_PROTOAUTO                   1027
#define IDC_PROTOV4                     1028
#define IDC_PROTOV6                     1029
#define IDC_PROP_NAME                   1030
#define IDC_FILEMOD2                    1030
#define IDC_PROP_OWNER                  1031
#define IDC_PROP_GROUP                  1032
#define IDC_PASSWORDHELP                1032
#define IDC_PROP_PERMISSIONS            1033
#define IDC_PROP_SIZE                   1034
#define IDC_PROP_MODIFIED               1035
#define IDC_PROP_RAWSTAT                1036
#define IDC_UTF8HELP                    1037
#define IDC_EDITPASS                    1038
#define IDC_NOPROXY                     1039
#define IDC_OTHERPROXY                  1040
#define IDC_SOCKS4APROXY                1041
#define IDC_SOCKS5PROXY                 1042
#define IDC_SYSTEM                      1043
#define IDC_USEAGENT                    1044
#define IDC_CERTFRAME                   1045
#define IDC_STATICPUB                   1046
#define IDC_STATICPEM                   1047
#define IDC_PROXYCOMBO                  1048
#define IDC_PROXYBUTTON                 1049
#define IDC_DELETELAST                  1050
#define IDC_SESSIONNAME                 1052
#define IDC_SHELLTRANSFER               1053
#define IDC_TRANSFERMODE                1054
#define IDC_PHPSHELL                    1055
#define IDC_PLUGINHELP                  1056
#define IDC_SYSTEMLABEL                 1057
#define IDC_CODEPAGELABEL               1058
#define IDC_CERTHELPPRIV                1059
#define IDC_PASSLABEL                   1060
#define IDS_LAN_PASSWORD_LABEL          280
#define IDS_LAN_MSG_RECEIVER_RUNNING    281
#define IDS_LAN_MSG_ACCEPTED            282
#define IDS_LAN_MSG_AUTO_LISTEN         283
#define IDS_STRING12001                 12001
#define IDS_STRING12002                 12002
#define IDS_STRING12003                 12003
#define IDS_STRING12004                 12004
#define IDS_STRING12005                 12005
#define IDS_STRING12006                 12006
#define IDS_STRING12007                 12007
#define IDS_STRING12008                 12008
#define IDS_STRING12009                 12009
#define IDS_STRING12010                 12010
#define IDS_STRING12011                 12011
#define IDS_STRING12012                 12012
#define IDS_STRING12013                 12013
#define IDS_STRING12014                 12014
#define IDS_STRING12015                 12015
#define IDS_STRING12016                 12016
#define IDS_STRING12017                 12017
#define IDS_STRING12018                 12018
#define IDS_STRING12019                 12019
#define IDS_STRING12020                 12020
#define IDS_STRING12021                 12021
#define IDS_STRING12022                 12022
#define IDS_STRING12023                 12023
#define IDS_STRING12024                 12024
#define IDS_STRING12025                 12025
#define IDS_STRING12026                 12026
#define IDS_STRING12027                 12027
#define IDS_STRING12028                 12028
#define IDS_STRING12029                 12029
#define IDS_STRING12030                 12030
#define IDS_STRING12031                 12031
#define IDS_STRING12032                 12032
#define IDS_STRING12033                 12033
#define IDS_STRING12034                 12034
#define IDS_STRING12035                 12035
#define IDS_STRING12036                 12036
#define IDS_STRING12037                 12037
#define IDS_STRING12038                 12038
#define IDS_STRING12039                 12039
#define IDS_STRING12040                 12040
#define IDS_STRING12041                 12041
#define IDS_STRING12042                 12042
#define IDS_STRING12043                 12043
#define IDS_STRING12044                 12044
#define IDS_STRING12045                 12045
#define IDS_STRING12046                 12046
#define IDS_STRING12047                 12047
#define IDS_STRING12048                 12048
#define IDS_STRING12049                 12049
#define IDS_STRING12050                 12050
#define IDS_STRING12051                 12051
#define IDS_STRING12052                 12052
#define IDS_STRING12053                 12053
#define IDS_LAN_ROLE_PROMPT             12054
#define IDS_LAN_SESSION_TIMEOUT         12055
#define IDC_LANPAIR_GROUP               1061
#define IDC_LAN_TIMEOUT                 1062
#define IDC_PERMISSIONS_GROUP           1063
#define IDC_FILEMOD_LABEL               1064
#define IDC_DIRMOD_LABEL                1065
#define IDC_LAN_TIMEOUT_LABEL           1066
#define IDC_LAN_TIMEOUT_HINT            1067

// ---------------------------------------------------------------------------
// Jump Host (ProxyJump) dialog controls
// ---------------------------------------------------------------------------
#define IDD_JUMPHOST                    115

#define IDC_JUMP_BUTTON                 1070   // "Jump..." button in main dialog
#define IDC_JUMP_ENABLE                 1071   // "Use jump host" checkbox in jump dialog
#define IDC_JUMP_HOST                   1072
#define IDC_JUMP_PORT                   1073
#define IDC_JUMP_USER                   1074
#define IDC_JUMP_PASSWORD               1075
#define IDC_JUMP_PUBKEY                 1076
#define IDC_JUMP_PRIVKEY                1077
#define IDC_JUMP_USEAGENT               1078
#define IDC_JUMP_LOADPUBKEY             1079
#define IDC_JUMP_LOADPRIVKEY            1080
#define IDC_JUMP_CRYPTPASS              1081
#define IDC_JUMP_EDITPASS               1082

// Control IDs for formerly IDC_STATIC labels (needed for runtime translation)
#define IDC_LABEL_CONNECTTO             1083
#define IDC_LABEL_USERNAME              1084
#define IDC_LABEL_CERTGROUP             1085
#define IDC_LABEL_TRANSFER              1086
#define IDC_LABEL_SESSION               1087
#define IDC_LABEL_JUMPHOST_GRP          1088
#define IDC_LABEL_PROXY_SETTINGS        1089
#define IDC_JUMP_GROUP                  1090
#define IDC_JUMP_LABEL_HOST             1091
#define IDC_JUMP_LABEL_PORT             1092
#define IDC_JUMP_LABEL_USER             1093
#define IDC_JUMP_LABEL_PASS             1094
#define IDC_JUMP_LABEL_PUBKEY           1095
#define IDC_JUMP_LABEL_PRIVKEY          1096
#define IDC_PROXY_GROUP                 1097
#define IDC_PROXY_LABEL_HOST            1098
#define IDC_PROXY_LABEL_USER            1099
#define IDC_PROXY_LABEL_PASS            1100

// ---------------------------------------------------------------------------
// Session picker dialog
// ---------------------------------------------------------------------------

// Dialog label string IDs for runtime localization via LNG loader
#define IDS_DLG_CAPTION                 284
#define IDS_DLG_CONNECTTO               285
#define IDS_DLG_USERNAME                286
#define IDS_DLG_USEAGENT                287
#define IDS_DLG_CHANGEPASS              288
#define IDS_DLG_CRYPTPASS               289
#define IDS_DLG_CERTGROUP               290
#define IDS_DLG_PUBKEY                  291
#define IDS_DLG_PRIVKEY                 292
#define IDS_DLG_COMPRESS                293
#define IDS_DLG_DETAILED_LOG            294
#define IDS_DLG_SHELLTRANSFER           295
#define IDS_DLG_SCP_DATA                296
#define IDS_DLG_SCP_ALL                 297
#define IDS_DLG_TRANSFER                298
#define IDS_DLG_ENCODING                299
#define IDS_DLG_PERMISSIONS_GROUP       300
#define IDS_DLG_FILEMOD                 301
#define IDS_DLG_DIRMOD                  302
#define IDS_DLG_SESSION                 303
#define IDS_DLG_JUMPHOST_GRP            304
#define IDS_DLG_USE_JUMPHOST            305
#define IDS_DLG_PROXY_SETTINGS          306
#define IDS_DLG_DELETELAST              307
#define IDS_PROXY_DLG_CAPTION           309
#define IDS_PROXY_DLG_GROUP             310
#define IDS_PROXY_DLG_HOST              311
#define IDS_PROXY_DLG_USER              312
#define IDS_PROXY_DLG_PASS              313
#define IDS_JUMP_DLG_CAPTION            314
#define IDS_JUMP_DLG_GROUP              315
#define IDS_JUMP_DLG_USE                316
#define IDS_JUMP_DLG_HOST               317
#define IDS_JUMP_DLG_PORT               318
#define IDS_JUMP_DLG_USER               319
#define IDS_JUMP_DLG_PASS               320
#define IDS_JUMP_DLG_PUBKEY             321
#define IDS_JUMP_DLG_PRIVKEY            322
#define IDS_JUMP_DLG_USEAGENT           323
#define IDS_BTN_HELP                    324
#define IDS_BTN_CANCEL                  325
#define IDS_DLG_PHP_TAR                 326
#define IDS_DLG_SYSTEM                  327
#define IDS_DLG_PHP_METHOD              328
#define IDS_DLG_PHP_CHUNKS              329
#define IDS_BTN_OK                      330
#define IDS_DLG_WIN_LINEBREAKS          450
#define IDS_DLG_UNIX_LINEBREAKS         451
#define IDS_PROXY_DLG_NOPROXY           452
#define IDS_PROXY_DLG_HTTP              453
#define IDS_PROXY_DLG_SOCKS4A           454
#define IDS_PROXY_DLG_SOCKS5            455
#define IDS_TRANSFERMODE_SSH            331
#define IDS_TRANSFERMODE_PHP_AGENT      332
#define IDS_TRANSFERMODE_PHP_SHELL      333
#define IDS_PHP_ERR_UNREACHABLE         334
#define IDS_PHP_ERR_NOT_FOUND           335
#define IDS_PHP_ERR_UNCONFIGURED        336
#define IDS_PHP_ERR_WRONG_CREDS_HTTP    337
#define IDS_PHP_ERR_REQUEST_FAILED      338
#define IDS_PHP_ERR_REJECTED            339
#define IDS_PHP_ERR_VALIDATION          340
#define IDS_PHP_ERR_WRONG_CREDS         341
#define IDS_PHP_SHELL_SELECT            342
#define IDS_PHP_SHELL_TITLE             343
#define IDS_PHP_AGENT_TITLE             344
#define IDS_PHP_COPY_FROM               345
#define IDS_PHP_UPLOAD_TO               346
#define IDS_PHP_CHECK_URL               347
#define IDS_PHP_PROBE_FAILED            348

// Log / status messages (349-414)
#define IDS_LOG_SCP_SKIP_PROBE          349
#define IDS_LOG_AUTH_METHODS_TIMEOUT    350
#define IDS_LOG_AUTH_METHODS_NONE       351
#define IDS_LOG_AUTH_NO_PASSWORD        352
#define IDS_LOG_KBD_AUTH_TIMEOUT        353
#define IDS_LOG_PASS_AUTH_TIMEOUT       354
#define IDS_LOG_LOADING_SSH_LIB         355
#define IDS_LOG_LAN_DISCOVER            356
#define IDS_LOG_LAN_CONNECTED           357
#define IDS_LOG_PHP_AGENT_MODE          358
#define IDS_LOG_POST_AUTH_INIT          359
#define IDS_LOG_SCP_RECONNECT           360
#define IDS_LOG_RECONNECT               361
#define IDS_LOG_SFTP_INIT               362
#define IDS_LOG_SEND_STORED_PASS        363
#define IDS_LOG_REQUEST_PASS            364
#define IDS_LOG_SEND_USER_PASS          365
#define IDS_LOG_PPK_ERR_VERSION         366
#define IDS_LOG_PPK_ERR_ALGO            367
#define IDS_LOG_PPK_ERR_ENC             368
#define IDS_LOG_PPK_ERR_ARGON2          369
#define IDS_LOG_PPK_ERR_PASSPHRASE      370
#define IDS_LOG_PPK_ERR_GENERIC         371
#define IDS_LOG_PPK_CONVERTING          372
#define IDS_LOG_PAGEANT_TIMEOUT         373
#define IDS_LOG_PUBKEY_TIMEOUT          374
#define IDS_LOG_JUMP_NO_FP              375
#define IDS_LOG_JUMP_AUTH_NONE          376
#define IDS_LOG_JUMP_AGENT_TRY          377
#define IDS_LOG_JUMP_AGENT_OK           378
#define IDS_LOG_JUMP_AGENT_FAIL         379
#define IDS_LOG_JUMP_PUBKEY_TRY         380
#define IDS_LOG_JUMP_PUBKEY_OK          381
#define IDS_LOG_JUMP_PUBKEY_FAIL        382
#define IDS_LOG_JUMP_PASS_TRY           383
#define IDS_LOG_JUMP_PASS_OK            384
#define IDS_LOG_JUMP_PASS_FAIL          385
#define IDS_LOG_JUMP_KBD_TRY            386
#define IDS_LOG_JUMP_KBD_OK             387
#define IDS_LOG_JUMP_KBD_FAIL           388
#define IDS_LOG_JUMP_AUTH_FAIL          389
#define IDS_LOG_PROXYJUMP               390
#define IDS_LOG_JUMP_SSH_FAIL           391
#define IDS_LOG_JUMP_HANDSHAKE          392
#define IDS_LOG_JUMP_HANDSHAKE_OK       393
#define IDS_LOG_JUMP_FP_REJECTED        394
#define IDS_LOG_JUMP_TCP_FAIL           395
#define IDS_LOG_JUMP_TCP_OK             396
#define IDS_LOG_JUMP_HANDSHAKE_FAIL     397
#define IDS_LOG_DETECT_UTF8             398
#define IDS_LOG_DETECT_LINEBREAK        399
#define IDS_LOG_USER_COMMAND            400
#define IDS_LOG_SCP64                   401
#define IDS_LOG_SCP_OPEN_TIMEOUT        402
#define IDS_LOG_SCP_DROPPED             403
#define IDS_LOG_SCP_SESSION_LOST        404
#define IDS_LOG_SCP_NO_SHELL            405
#define IDS_LOG_SCP_LIST_FAIL           406
#define IDS_LOG_SCP_MKDIR_FAIL          407
#define IDS_LOG_SFTP_OPEN_TIMEOUT       408
#define IDS_LOG_SCP_DL_TIMEOUT          409
#define IDS_LOG_SCP_UL_TIMEOUT          410
#define IDS_LOG_SHELL_DL_START          411
#define IDS_LOG_SHELL_BASE64            412
#define IDS_LOG_SHELL_UL_START          413
#define IDS_LOG_PHP_SKIP_UPDATE         414
#define IDS_LOG_TAR_UPLOAD              415
#define IDS_LOG_TAR_UPLOAD_FAIL         416
#define IDS_DLG_SELECT_PUBKEY           417
#define IDS_DLG_SELECT_PRIVKEY          418
#define IDS_PROXY_LABEL_SOCKS4A         426
#define IDS_PROXY_LABEL_SOCKS5          427
#define IDS_DLG_CODEPAGE_TITLE          428
#define IDS_DLG_CODEPAGE_PROMPT         429

#define IDC_PHP_TAR                     1105
#define IDS_SCP_PROTOCOL_ERROR          12072
#define IDS_SCP_EXEC_FAILED             12073
#define IDS_LAN_ERR_NO_PEER             12074
#define IDS_LAN_ERR_PEER_NOT_FOUND      12075
#define IDS_ERR_INVALID_PROXY           12076
#define IDS_ERR_NOT_SUPPORTED           12077
#define IDS_ERR_NO_PLUGIN_DIR           12078
#define IDS_ERR_JUMP_SESSION            12079
#define IDS_ERR_LOAD_PASS               12080
#define IDS_ERR_LOAD_PROXY_PASS         12081
#define IDS_ERR_INVALID_SERVER          12082
#define IDS_ERR_OOM_CONN_SETTINGS       12083
#define IDS_ERR_SESSION_EXISTS          12088
#define IDS_TITLE_SFTP                  12089

// ---------------------------------------------------------------------------
// LAN Pair progress dialog
// ---------------------------------------------------------------------------
#define IDD_PAIRING_PROGRESS            117
#define IDC_PAIRING_STATUS              1106
#define IDC_PAIRING_COUNTDOWN           1107
#define IDS_PAIRING_SEARCH              12090
#define IDS_PAIRING_SECS                12091
#define IDS_PAIRING_TIMEOUT             12092

// ---------------------------------------------------------------------------
// LAN Pair — TrustedInstaller checkbox
// ---------------------------------------------------------------------------
#define IDC_LAN_TI                      1108
#define IDC_JUMP_SESSION_PICK           1109   // dropdown: pick existing session as jump host (in IDD_CONNECTION)
#define IDS_LAN_TI                      12093
#define IDS_LAN_TI_ERR                  12094
#define IDS_LAN_CONNECTING              12095
#define IDS_LAN_ERR_CONN_FAILED         12096
#define IDS_LAN_ERR_DONOR_NO_CONNECT    12103
#define IDS_JUMP_SESSION_NONE           12104   // "(none)" entry in jump-session dropdown
#define IDS_JUMP_SESSION_MISSING_SUFFIX 12105   // " (missing)" appended to deleted ref'd session name
#define IDS_JUMP_SESSION_NOT_FOUND      12106   // error: ref'd session not in INI
#define IDS_JUMP_SESSION_CHAINED        12107   // error: ref'd session has its own jump host
#define IDS_SIMPORT_TITLE               12109   // MessageBox title for session-INI import errors
#define IDS_SIMPORT_ERR_OPEN            12110   // Cannot open source file
#define IDS_SIMPORT_ERR_EMPTY           12111   // Source file empty
#define IDS_SIMPORT_ERR_NO_SECTIONS     12112   // File has no INI sections
#define IDS_SIMPORT_ERR_NO_SERVER       12113   // No section with server= key
#define IDS_SIMPORT_ERR_EMPTY_DEST      12114   // Empty destination path
#define IDS_SIMPORT_ERR_WRITE           12115   // Failed to write to sftpplug.ini
#define IDS_DLG_JUMP_BUTTON             12116   // "Jump..." button in the connection dialog
#define IDS_JUMP_NOT_CONFIGURED         12117   // error: jump host enabled but not configured

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

